### PR TITLE
feat: extracting all possible values from schema

### PR DESCRIPTION
**Pull request by mojtabaimani**
# User story
Generate a markdown table containing all possible otomi input values from values-schema automatically to be used in chart/otomi/README.md or any other documentations. This table should have these columns: 
* parameter
* type 
* description 
* default   

## Use cases
1. Dev can run this task to generate the table and use it to update documentations. 
2. This task can be used in Github actions, so whenever changes happen to values-schema.yaml in master branch, it will update the chart/otomi/readme.md or other readme files. 
3. There can be a pipeline that if there is any change in values-schema.yaml file, then an issue in github is generated automatically then someone should run this task and update the relevant documentations asap. 

## Definition Of Ready

- [ ] The story use cases are clear and described in Gherkin
- [ ] Requirements and use cases have been reviewed (in our daily session -- the developers rotate -- everyone is responsible!)
- [ ] The story is self-contained and has no dependencies on other stories
- [ ] The story has been estimated in complexity points
- [ ] Atomic SMART tasks have been created that reflect the functional requirements
- [ ] Atomic SMART tasks reflect any dependencies on other tasks in this story (affecting order of delivery)
- [ ] The story is reviewed and approved by @srodenhuis or @morriz

## Definition Of Done

- [ ] [Tasks](##Tasks) are done.
- [ ] Unit Tests are added with the code (if relevant and practical)
- [ ] Functional Tests are written down (if relevant and practical)
- [ ] Functional Tests are performed by another developer/ tester(if relevant and practical)
- [ ] (Architecture) Design Record(s) have been added as `adr/*.md` and appended to list in `adr/_index.md`.
- [ ] Schema and demo files have been updated to reflect code changes (if relevant).
- [ ] Documentation has been updated (if relevant).
- [ ] Functionality, code, and/or documentation have been peer reviewed.

### CODE REVIEW

**Comment by Morriz** [comment]
why does this exist again?

**Comment by mojtabaimani** [comment]
> why does this exist again?

I used this functions to generate the two tables in this file: https://github.com/redkubes/redkubes.github.io/blob/moj/chart-docs-modify/docs/inst-chart.md . no manual modification

**Comment by Morriz** [comment]
Ok, that is still a work in progress then to create the full values. I see the logic is not correct and it still produces branches. If you notice missing descriptions you have to take them from otomi-api as agreed before...

**Comment by Morriz** [comment]
I would love to see a description (and in it that this "closes #issuenr") so it is clear what this belongs to or does.

**Comment by Morriz** [comment]
this stuff can be moved to core if it is valuable @mojtabaimani

**Comment by Dunky13** [comment]
I was already working on/have already made (not sure which) a similar function in core. To extract the default values. Or any value based on a leaf keyword. Not sure if it still exists or not. Let's discuss

**Comment by svatwork** [comment]
It would be cool if this sets up a job in the relevant repository to keep the documentation up to date?

**Comment by mojtabaimani** [comment]
The width of values are too long and doesn't fit in the screen and needs a lot of horizontal scrolling. Do you have any idea?

**Comment by Morriz** [comment]
> The width of values are too long and doesn't fit in the screen and needs a lot of horizontal scrolling. Do you have any idea?

When looking at other charts out there I see nobody cares about line length when it comes to the table in the readme...

**Comment by Morriz** [comment]
I see that other charts generate the readme table as well (i.e. keycloak). So can we re-use similar logic?

**Comment by mojtabaimani** [comment]
I just deleted extra not-needed functions and generated the output based on the current values-schema.yaml. You can see the result in a temporary file here: https://github.com/redkubes/otomi-tasks/blob/moj/required-values/allValues.md 

I think the default column is not complete because currently we have other defaults in other places in code base. So it is not possible to generate them automatically now. I just extracted the defaults that are in schema. I suggest we delete the default column until we develop our consistent default mechanism.

**Comment by mojtabaimani** [comment]
Some other charts like keycloak they don't have type column because you can infer the type from default values. But they have default values for all possible values. We don't have default values for most of them and thats why we have nil in the table. nil means it is not defined by default and it is different with empty string or false or empty object. So, what is your suggestion? keeping the default column with 'nil' or empty default cells in the table if they are nil or remove the whole default column?

**Comment by Morriz** [comment]
just don't fill the cell if `nil` I would say

**Pull request closed without merging**
